services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eduvision_backend
    ports:
      - "8000:8000"
    networks:
      - eduvision_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduvision_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eduvision_network
    restart: unless-stopped

networks:
  eduvision_network:
    driver: bridge
